# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aggregate <- function(x, f) {
    .Call(`_epigraHMM_aggregate`, x, f)
}

computeBIC <- function(hdf5, numPar, numSamples) {
    .Call(`_epigraHMM_computeBIC`, hdf5, numPar, numSamples)
}

computeQFunction <- function(hdf5, pi, gamma) {
    .Call(`_epigraHMM_computeQFunction`, hdf5, pi, gamma)
}

computeViterbiSequence <- function(hdf5, pi, gamma) {
    .Call(`_epigraHMM_computeViterbiSequence`, hdf5, pi, gamma)
}

consensusRejectionControlled <- function(hdf5, f, p) {
    .Call(`_epigraHMM_consensusRejectionControlled`, hdf5, f, p)
}

differentialRejectionControlled <- function(hdf5, f, p, N) {
    .Call(`_epigraHMM_differentialRejectionControlled`, hdf5, f, p, N)
}

expStep <- function(pi, gamma, logf, hdf5) {
    invisible(.Call(`_epigraHMM_expStep`, pi, gamma, logf, hdf5))
}

getMarginalProbability <- function(hdf5) {
    .Call(`_epigraHMM_getMarginalProbability`, hdf5)
}

innerMaxStepProb <- function(hdf5) {
    .Call(`_epigraHMM_innerMaxStepProb`, hdf5)
}

maxStepProb <- function(hdf5) {
    .Call(`_epigraHMM_maxStepProb`, hdf5)
}

rbinomVectorized <- function(prob) {
    .Call(`_epigraHMM_rbinomVectorized`, prob)
}

reweight <- function(x, p) {
    .Call(`_epigraHMM_reweight`, x, p)
}

simulateMarkovChain <- function(P, n) {
    .Call(`_epigraHMM_simulateMarkovChain`, P, n)
}

