# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aggregate <- function(x, f) {
    .Call(`_epigraHMM_aggregate`, x, f)
}

expStep <- function(counts, pi, gamma, logf, nameForwardProb, nameBackwardProb, nameMarginalProb, nameJointProb) {
    invisible(.Call(`_epigraHMM_expStep`, counts, pi, gamma, logf, nameForwardProb, nameBackwardProb, nameMarginalProb, nameJointProb))
}

getMarginalProbability <- function(nameMarginalProb) {
    .Call(`_epigraHMM_getMarginalProbability`, nameMarginalProb)
}

getViterbiSequence <- function(nameForwardProb, pi, gamma) {
    .Call(`_epigraHMM_getViterbiSequence`, nameForwardProb, pi, gamma)
}

maxStepProb <- function(nameMarginalProb, nameJointProb) {
    .Call(`_epigraHMM_maxStepProb`, nameMarginalProb, nameJointProb)
}

rbinomVectorized <- function(prob) {
    .Call(`_epigraHMM_rbinomVectorized`, prob)
}

rejectionControlled <- function(nameMarginalProb, f, p) {
    .Call(`_epigraHMM_rejectionControlled`, nameMarginalProb, f, p)
}

reweight <- function(x, p) {
    .Call(`_epigraHMM_reweight`, x, p)
}

simulateMarkovChain <- function(P, n) {
    .Call(`_epigraHMM_simulateMarkovChain`, P, n)
}

